
export interface GuideStep {
  title: string;
  description: string;
  tips?: string[];
  /** Exact runnable commands for this step; each links to the explainer. */
  commands?: string[];
  actionLabel?: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  visualCue?: string;
  imageUrl?: string;
}

export interface FAQItem {
  question: string;
  answer: string;
}

export enum ExploringMode {
  STANDARD = 'Standard',
  EXPERT = 'Expert'
}

export interface Tutorial {
  id: string;
  name: string;
  category: Category;
  description: string;
  icon: string;
  color: string;
  popularTopics: string[];
  advancedTopics: string[];
  versions: string[]; 
}

export type CommandOS = 'Windows' | 'macOS' | 'Linux';

/** A token's meaning is always relative to the command it appears in. */
export interface CommandPart {
  token: string;
  kind: 'command' | 'subcommand' | 'flag' | 'value' | 'path' | 'operator';
  meaning: string;
}

export interface CommandExplanation {
  normalized: string;
  os: string;
  summary: string;
  plainEnglish: string;
  risk: 'safe' | 'caution' | 'destructive';
  riskNote?: string;
  parts: CommandPart[];
  commonFlags: { flag: string; meaning: string }[];
  examples: { command: string; description: string }[];
  cautions?: string[];
}

export interface AIResponse {
  steps: GuideStep[];
  overview: string;
  /** Plain-English statement of what this is and the problem it solves. */
  whatItIs?: string;
  /** Concrete situations a reader would actually reach for it. */
  whenToUse?: string[];
  /**
   * How access is actually obtained. Not always an installation — a hosted
   * service is signed up for, an MCP server is configured in a client, and
   * something shipped with the OS needs nothing at all.
   */
  howYouGetIt?: string;
  /**
   * Pages the guide was grounded in. Attached server-side from the real search
   * results, never generated by the model, so every link actually exists.
   */
  sources?: { title: string; url: string }[];
  /** Empty for anything without a keyboard interface — a CLI, API or protocol. */
  commonShortcuts: { key: string; action: string }[];
  beginnerChecklist: string[];
  faqs: FAQItem[];
}

export enum Category {
  OS = 'OS',
  SECURITY = 'Security',
  OFFICE = 'Office',
  PRODUCTIVITY = 'Productivity',
  CREATIVE = 'Creative',
  DEV = 'Development',
  DEVOPS = 'DevOps',
  CLOUD = 'Cloud Infrastructure',
  ENTERPRISE = 'Enterprise Systems',
  WEB = 'Web Platforms',
  ENGINEERING = 'Engineering & CAD',
  GAMING = 'Gaming Platforms',
  FINANCE = 'Finance & ERP',
  SOCIAL_MEDIA = 'Social & Marketing',
  COMMUNICATION = 'Communication',
  STREAMING = 'Streaming & Media',
  E_COMMERCE = 'Marketplaces',
  DESIGN = 'Design Tools',
  COLLABORATION = 'Team Collaboration'
}
